[package]
name = "jj-release"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
git-conventional = "1.1.0"
jiff = "0.2.35"
semver = "1.0.28"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
toml = "1.1.5"
toml_edit = "0.25.13"
which = "8.0.6"

[dev-dependencies]
tempfile = "3"
