# Generated by rust2rpm 28
%bcond check 1

%global crate jj-release

Name:           rust-jj-release
Version:        0.8.0
Release:        %autorelease
Summary:        Semantic releases for Jujutsu VCS repositories

License:        Apache-2.0
URL:            https://crates.io/crates/jj-release
Source0:        %{crates_source}
Source1:        vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Semantic releases for Jujutsu VCS repositories.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        Apache-2.0
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/jj-release

%prep
%autosetup -n %{crate}-%{version} -p1 -a 1
%cargo_prep -v vendor


%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
