[package]
name = "jj-release"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
documentation.workspace = true
exclude.workspace = true

[[bin]]
name = "jj-release"
path = "src/main.rs"

[dependencies]
jj_release_core = { path = "../lib", version = "0.5.2" }
toml_edit = { version = "0.25.15", default-features = false }
clap = { version = "4.6.7", default-features = false, features = [
  "derive",
  "help",
  "std",
  "usage",
] }
semver = { version = "1.0.28", default-features = false }

[lints]
workspace = true
