use std::{borrow, fmt::Write, fs, path::Path};

use anyhow::Result;

pub fn init(root: &Path) -> Result<()> {
    use jj_release::detect;

    let release_toml = root.join("release.toml");
    if release_toml.exists() {
        println!("release.toml already exists. Delete it first to reinitialize.");
        return Ok(());
    }

    // Detect forge.
    let forge = detect::detect_forge(root).unwrap_or("github");
    println!("→ Detected forge: {forge}");

    // Check CLI tool availability.
    if forge == "github" && !detect::tool_available("gh") {
        eprintln!("warning: forge is github but gh CLI not found on PATH");
        eprintln!("  install: https://cli.github.com");
    }
    if forge == "gitlab" && !detect::tool_available("glab") {
        eprintln!("warning: forge is gitlab but glab CLI not found on PATH");
        eprintln!("  install: https://gitlab.com/gitlab-org/cli");
    }

    // Detect language.
    let language = detect::detect_language(root).unwrap_or("cargo");
    println!("→ Detected language: {language}");

    // Detect workspace.
    let workspace_toml = root.join("Cargo.toml");
    let is_workspace = workspace_toml.exists() && {
        let content = fs::read_to_string(&workspace_toml).unwrap_or_default();
        content.contains("[workspace]")
    };

    // Build the config.
    let mut content = format!(
        r#"# Generated by jj-release init

[release]
forge = "{forge}"
create_release = false

[publish]
cargo = {}

[changelog]
enabled = true

manifest_backend = "{language}"
"#,
        language == "cargo"
    );

    // Detect workspace members from Cargo.toml.
    if is_workspace {
        println!("→ Detected workspace");

        // Try to parse members from [workspace] table.
        let members = parse_workspace_members(&workspace_toml);

        let versioning = detect::detect_versioning(&workspace_toml);
        println!("→ Detected versioning: {versioning}");
        let member_config = if members.is_empty() {
            r#"
# Add your workspace members below:
# [[workspace.members]]
# name = "mylib"
# path = "lib"
# publish = true
"#
            .to_owned()
        } else {
            let mut s = String::new();
            for (name, path) in &members {
                println!("  → Found member: {name} ({path})");
                let tag_prefix = if versioning == "independent" {
                    format!("\ntag_prefix = \"{name}-v\"")
                } else {
                    String::new()
                };
                let _ = write!(
                    s,
                    "\n[[workspace.members]]\nname = \"{name}\"\npath = \"{path}\"\npublish = true{tag_prefix}\n# depends_on = [] # add names of members this depends on\n"
                );
            }
            s
        };

        let _ = write!(
            content,
            "\n[workspace]\nenabled = true\nversioning = \"{versioning}\"\n{member_config}"
        );
    }

    fs::write(&release_toml, content)?;
    println!("✓ Written release.toml");

    Ok(())
}

fn parse_workspace_members(cargo_toml: &Path) -> Vec<(String, String)> {
    let Ok(raw) = fs::read_to_string(cargo_toml) else {
        return vec![];
    };
    let Ok(doc) = raw.parse::<toml_edit::DocumentMut>() else {
        return vec![];
    };
    let Some(members) = doc
        .get("workspace")
        .and_then(|w| w.get("members"))
        .and_then(|m| m.as_array())
    else {
        return vec![];
    };

    members
        .iter()
        .filter_map(|m| m.as_str())
        .map(|path| {
            let member_toml = cargo_toml.parent().unwrap().join(path).join("Cargo.toml");
            let raw = fs::read_to_string(&member_toml).ok();
            let doc = raw
                .as_deref()
                .and_then(|r| r.parse::<toml_edit::DocumentMut>().ok());

            let name = doc
                .as_ref()
                .and_then(|d: &toml_edit::DocumentMut| {
                    d.get("package")
                        .and_then(|p| p.get("name"))
                        .and_then(|n| n.as_str())
                        .map(borrow::ToOwned::to_owned)
                })
                .unwrap_or_else(|| path.split('/').next_back().unwrap_or(path).to_owned());

            (name, path.to_owned())
        })
        .collect::<Vec<_>>()
}
