use std::{fmt::Write, fs, path::Path};

use jj_release_core::{config::Versioning, detect, errors::Result, workspace};

pub fn init(root: &Path) -> Result<()> {
    let release_toml = root.join("release.toml");
    if release_toml.exists() {
        println!("release.toml already exists. Delete it first to reinitialize.");
        return Ok(());
    }

    // Detect forge.
    let forge = detect::detect_forge(root).unwrap_or("github");
    println!("→ Detected forge: {forge}");

    // Check CLI tool availability.
    if forge == "github" && !detect::tool_available("gh") {
        eprintln!("warning: forge is github but gh CLI not found on PATH");
        eprintln!("  install: https://cli.github.com");
    }
    if forge == "gitlab" && !detect::tool_available("glab") {
        eprintln!("warning: forge is gitlab but glab CLI not found on PATH");
        eprintln!("  install: https://gitlab.com/gitlab-org/cli");
    }

    // Detect language.
    let language = detect::detect_language(root).unwrap_or("cargo");
    println!("→ Detected language: {language}");

    // Build the config.
    let mut content = format!(
        r#"# Generated by jj-release init

[release]
forge = "{forge}"
create_release = false

[publish]
cargo = false

[changelog]
enabled = true

manifest_backend = "{language}"
"#,
    );

    // Detect workspace members from Cargo.toml.
    if let Some(ws) = workspace::detect_workspace(root)? {
        println!("→ Detected workspace");

        let versioning = match ws.versioning {
            Versioning::Independent => "independent",
            Versioning::Unified => "unified",
        };
        println!("→ Detected versioning: {versioning}");

        let member_config = if ws.members.is_empty() {
            r#"
# Add your workspace members below:
# [[workspace.members]]
# name = "mylib"
# path = "lib"
# publish = true
"#
            .to_owned()
        } else {
            let mut s = String::new();
            for member in &ws.members {
                println!("  → Found member: {} ({})", member.name, member.path);
                let tag_prefix = if versioning == "independent" {
                    format!("\ntag_prefix = \"{}-v\"", member.name)
                } else {
                    String::new()
                };
                let _ = write!(
                    s,
                    "\n[[workspace.members]]\nname = \"{}\"\npath = \"{}\"\npublish = true{tag_prefix}\n# depends_on = [] # add names of members this depends on\n",
                    member.name, member.path
                );
            }
            s
        };

        let _ = write!(
            content,
            "\n[workspace]\nenabled = true\nversioning = \"{versioning}\"\n{member_config}"
        );
    }

    fs::write(&release_toml, content)?;
    println!("✓ Written release.toml");

    Ok(())
}
